### ISSUE TITLE
hello，master

### ISSUE THREAD

**Issue by wenzheng-wen** [korosenpai/esp32-compass#1]
emmm，I show up when I'm running the code：ImportError: no module named 'mpu9250.mpu9250'，Why is that? Please answer###

**Comment by korosenpai** [comment]
did you flash in the esp32 only the code in the folder "esp32" or everything?
if you put everything try importing "esp32.mpu9250.mpu9250" as when you run the code you are automatically transported  in the root directory, but i suggest you flash in the esp32 only the files in the "esp32" folder and it should work

sorry for the late response i didnt expect anyone here ahaha

**Comment by korosenpai** [comment]
i forgot to add documentation lol, the code in the root dir should run on your computer, while the code in the "esp32" folder should be in your esp32.
you need to connect the esp32 with usb to pc and set the correct serial port in line 11 in compass.py

**Comment by wenzheng-wen** [comment]
Thank you for your reply.I'll take your advice：）

**Comment by korosenpai** [comment]
lemme know if it works :)
